app/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from werkzeug.security import generate_password_hash
# from datetime import datetime

db = SQLAlchemy()

My_Pokemon = db.Table('My_Pokemon',
                      db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
                      db.Column('pokemon_name', db.String, db.ForeignKey('pokemon.name'))
)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, unique=True, nullable=False)
    email = db.Column(db.String, unique=True, nullable=False)
    password =db.Column(db.String, nullable=False)
    catch = db.relationship('Pokemon', secondary=My_Pokemon,  lazy='dynamic')
        

    def __init__(self, username, email, password):

        self.username  = username
        self.email = email
        self.password =  generate_password_hash(password)


    def save(self):  
        db.session.add(self)  
        db.session.commit() 



class Pokemon(db.Model):
    name = db.Column(db.String, primary_key=True)
    base_hp = db.Column(db.Integer,  nullable=False)
    base_attack = db.Column(db.Integer,  nullable=False)
    base_defense = db.Column(db.Integer,  nullable=False)
    sprite_img = db.Column(db.String(200),  nullable=False)





    def __init__(self,name, base_hp, base_attack, base_defense,sprite_img):
        self.name = name
        self.base_hp = base_hp
        self.base_attack = base_attack
        self.base_defense = base_defense
        self.sprite_img = sprite_img



def save(self):
        db.session.add(self)
        db.session.commit()



# class User(db.Model, UserMixin):
#     id = db.Column(db.Integer, primary_key=True)
#     username = db.Column(db.String, unique=True, nullable=False)
#     email = db.Column(db.String, unique=True, nullable=False)
#     password = db.Column(db.String, nullable=False)
    
#     def __init__(self, username, email, password):
#         self.username = username
#         self.email = email
#         self.password = generate_password_hash(password)

#     def save(self):
#         db.session.add(self)
#         db.session.commit()

# class post(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     img_url = db.Column(db.String, nullable=False)
#     caption = db.Column(db.String, nullable=False)
#     location = db.Column(db.String, nullable=True)
#     date = db.Column(db.DateTime, default=datetime.utcnow(), nullable=False)
#     user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

#     def __init__(self, img_url, caption, user_id, location=''):
#         self.img_url = img_url
#         self.caption = caption
#         self.user_id = user_id
#         self.location = location

    # def save(self):
    #     db.session.add(self)
    #     db.session.commit()

app/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField
from wtforms.validators import DataRequired



class PokemonForm(FlaskForm):
    name_or_id = StringField('Name_or_id: ', validators=[DataRequired()])
    submit_btn = SubmitField('Search')

class BattleForm(FlaskForm):
    username = StringField('Name_or_id: ', validators=[DataRequired()])
    submit_btn = SubmitField('find opponent')

app/__init__.py
from flask import Flask
from config import Config
from flask_login import LoginManager
from app.models import db, User
from flask_migrate import Migrate
# from app.blueprints.main import main
# from app.blueprints.auth import auth


app = Flask(__name__)
app.config.from_object(Config)

login_manager = LoginManager()

login_manager.init_app(app)
db.init_app(app)
migrate = Migrate(app, db)

login_manager.login_view = 'auth.login'
login_manager.login_message = 'please login first!'
login_manager.login_message_category = 'danger'


from app.blueprints.auth import auth
from app.blueprints.main import main


app.register_blueprint(auth)
app.register_blueprint(main)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/blueprints/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder= 'main_templates')

from . import routes

app/blueprints/main/routes.py
from . import main
from flask import render_template, request, flash, url_for,  redirect
import requests
from .forms import PokemonForm, BattleForm
from  app.models import Pokemon, db, User, My_Pokemon 

from flask_login import current_user, login_required


@main.route("/")
def home():
    return render_template('home.html')

@main.route('/user/<name>')
def user(name):
    return f'hello {name}'





def get_pokemon_data(name):
    url = f'https://pokeapi.co/api/v2/pokemon/{name}'
    response = requests.get(url)
    output=[]
    if response.ok:
        data = response.json()
        return {
            'name': data['name'].capitalize(),
            'hp': data['stats'][0]['base_stat'],
            'defense': data['stats'][3]['base_stat'],
            'attack': data['stats'][1]['base_stat'],
            'sprite': data['sprites']['front_shiny'],
            'ability': data['abilities'][0]['ability']['name']
        }
    else:
        return output.append
pokemon_names = ['charizard', 'pikachu', 'squirtle', 'bulbasaur', 'charmander', 'raichu']

@main.route('/pokemon', methods=['GET', 'POST'])
def pokemon():
    form = PokemonForm()
    if request.method == 'POST' and form.validate_on_submit:
        pokemon_identifier = form.name_or_id.data
        print(pokemon_identifier)
        pokemons = get_pokemon_data(pokemon_identifier)
        return render_template('pokemon.html', pokemons=pokemons, form=form)
    else:
        return render_template('pokemon.html', form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%} {%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {%block  styles%} {%endblock%}
</head>
<body>
    {%block content%}


    {%endblock%}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>  
</body>
</html>

app/templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Pokemon World</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('main.home') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('main.pokemon') }}">Pokemon</a>
          </li>
          {% if current_user.is_anonymous %}
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('auth.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('auth.signup') }}">Sign Up</a>
          </li>
          {%else%}
          <li class="nav-item"></li>
            <a class="nav-link active" href="{{url_for('main.team')}}">Team</a>
          </li>
          <li class="nav-item"></li>
            <a class="nav-link active" href="{{url_for('main.battle')}}">Battle</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('auth.logout') }}">Logout</a>
          </li>
          {%endif%}
        </ul>
      </div>
      {% if current_user.is_authenticated %}
      <h4 class="mr-3">{{ current_user.username }}</h4>
      {%endif%}
    </div>
  </nav>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
     {% for category, message in messages %}
        <div clss="alert alert {{ category }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  